# Generated by Django 6.0.2 on 2026-02-18 17:29

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography'), ('Art', 'Art'), ('Music', 'Music'), ('PE', 'PE'), ('Computing', 'Computing'), ('Design & Technology', 'Design & Technology'), ('MFL', 'MFL'), ('Citizenship', 'Citizenship'), ('Cookery', 'Cookery'), ('Other', 'Other')], max_length=50)),
                ('year_group', models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4'), ('Year 5', 'Year 5'), ('Year 6', 'Year 6'), ('KS3', 'KS3'), ('KS4', 'KS4'), ('KS5', 'KS5'), ('Other', 'Other')], max_length=50)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='resource_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
